### ISSUE TITLE
Add github actions

### ISSUE THREAD

**Issue by mstanciu552** [EddieJaoudeCommunity/EddieCommunityApi#9]
We should add github actions here.
It could be similar to [EddieBot](https://github.com/EddieJaoudeCommunity/EddieBot).
I would like to do this but it would be my first time and I have to learn it first and practice on one of my repos.

If you wouldn't mind I could do it in 2 or 3 days.

**Comment by Vyvy-vi** [comment]
This is needed. 👍 
However, I think there is already an issue open for this(issue #2)
Perhaps you could send this message on that issue so that you could get assigned?

(IMHO duplicate issues cause difficulties for maintainers)

**Additional Context**:
All the repositories are supposed to use the same actions.
You could look at examples at: https://github.com/EddieJaoudeCommunity/support/tree/main/.github/workflows
(we need to make same workflows here)

You could also checkout github's documentation for workflows and actions, to get more in-depth detail for gh-actions:
https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions

**Comment by mstanciu552** [comment]
oh yeah just noticed.

I will move it there
